/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBtcWatchRouteImport } from './routes/api/btc/watch'
import { Route as ApiNexapayWebhookRouteImport } from './routes/api/nexapay/webhook'
import { Route as PayBtcTokenRouteImport } from './routes/pay/btc/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBtcWatchRoute = ApiBtcWatchRouteImport.update({
  id: '/api/btc/watch',
  path: '/api/btc/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNexapayWebhookRoute = ApiNexapayWebhookRouteImport.update({
  id: '/api/nexapay/webhook',
  path: '/api/nexapay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBtcTokenRoute = PayBtcTokenRouteImport.update({
  id: '/pay/btc/$token',
  path: '/pay/btc/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/btc/watch': typeof ApiBtcWatchRoute
  '/api/nexapay/webhook': typeof ApiNexapayWebhookRoute
  '/pay/btc/$token': typeof PayBtcTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/btc/watch': typeof ApiBtcWatchRoute
  '/api/nexapay/webhook': typeof ApiNexapayWebhookRoute
  '/pay/btc/$token': typeof PayBtcTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/btc/watch': typeof ApiBtcWatchRoute
  '/api/nexapay/webhook': typeof ApiNexapayWebhookRoute
  '/pay/btc/$token': typeof PayBtcTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/btc/watch'
    | '/api/nexapay/webhook'
    | '/pay/btc/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/btc/watch'
    | '/api/nexapay/webhook'
    | '/pay/btc/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/btc/watch'
    | '/api/nexapay/webhook'
    | '/pay/btc/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBtcWatchRoute: typeof ApiBtcWatchRoute
  ApiNexapayWebhookRoute: typeof ApiNexapayWebhookRoute
  PayBtcTokenRoute: typeof PayBtcTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/btc/watch': {
      id: '/api/btc/watch'
      path: '/api/btc/watch'
      fullPath: '/api/btc/watch'
      preLoaderRoute: typeof ApiBtcWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nexapay/webhook': {
      id: '/api/nexapay/webhook'
      path: '/api/nexapay/webhook'
      fullPath: '/api/nexapay/webhook'
      preLoaderRoute: typeof ApiNexapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/btc/$token': {
      id: '/pay/btc/$token'
      path: '/pay/btc/$token'
      fullPath: '/pay/btc/$token'
      preLoaderRoute: typeof PayBtcTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBtcWatchRoute: ApiBtcWatchRoute,
  ApiNexapayWebhookRoute: ApiNexapayWebhookRoute,
  PayBtcTokenRoute: PayBtcTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
